platform:ios,'7.0'

pod 'JSAnimatedImagesView'
pod 'BZGFormField'
pod 'TSMessages'
pod 'RESideMenu', '~> 3.4'
pod 'RNFrostedSidebar'
pod 'RNGridMenu'
pod 'MBProgressHUD'
pod 'Parse-iOS-SDK'
pod 'DropdownMenu'
pod 'SDWebImage'
pod 'MRProgress', '~> 0.3'
pod 'Bolts'
pod 'SwipeView'