platform:ios,'7.0'

pod 'JSAnimatedImagesView'
pod 'BZGFormField'
pod 'TSMessages'
pod 'RESideMenu', '~> 3.4'
pod 'RNFrostedSidebar'
pod 'RNGridMenu'
pod 'MBProgressHUD'
pod 'Parse-iOS-SDK'
pod 'SDWebImage'
pod 'MRProgress', '~> 0.3'
pod 'Bolts','~> 1.1.0'
pod 'SwipeView'
pod 'FaceAwareFill'
pod 'RPFloatingPlaceholders'
pod 'RegExCategories'
pod 'ASMediaFocusManager'
pod 'EAIntroView'
pod 'ReactiveCocoa'